; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; ============================================================
; PlatformIO Project Configuration
; ============================================================

[platformio]
default_envs = uno_r4_m

; ------------------------------------------------------------
; Arduino Nano (ATmega328P, new bootloader)
; ------------------------------------------------------------
[env:nano]
platform = atmelavr
board = nanoatmega328new
extra_scripts = pre:extra_script.py
framework = arduino


lib_deps =
    adafruit/Adafruit MPU6050@^2.2.4
    adafruit/Adafruit BMP280 Library@^2.6.6
    adafruit/Adafruit Unified Sensor@^1.1.9
    coryjfowler/mcp_can
    BasicLinearAlgebra
    mikalhart/TinyGPSPlus

; Optional: stricter checks / consistency
check_tool = cppcheck
check_flags =
    cppcheck: --enable=all --std=c++17
check_skip_packages = yes


; ------------------------------------------------------------
; Arduino Uno R4 Minima (Renesas RA4M1)
; ------------------------------------------------------------
[env:uno_r4_m]
platform = renesas-ra
board = uno_r4_minima
extra_scripts = pre:extra_script.py
framework = arduino


lib_deps =
    adafruit/Adafruit MPU6050@^2.2.4
    adafruit/Adafruit BMP280 Library@^2.6.6
    adafruit/Adafruit Unified Sensor@^1.1.9
    coryjfowler/mcp_can
    BasicLinearAlgebra
    mikalhart/TinyGPSPlus

; Helps both build + clangd
build_flags =
    -std=gnu++17

check_tool = cppcheck
check_flags =
    cppcheck: --enable=all --std=c++17
check_skip_packages = yes

